<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Treehouse.Example</AssemblyName>
    <RootNamespace>Treehouse.Example</RootNamespace>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <BaseOutputPath>$(SolutionDir)Build\$(Configuration)\Example</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Runtime\Runtime.csproj" />
  </ItemGroup>

</Project>
