<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Treehouse.Runtime</AssemblyName>
    <RootNamespace>Treehouse.Runtime</RootNamespace>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseOutputPath>$(SolutionDir)Build\Runtime</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);TREEHOUSE_RUNTIME_DEBUG</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);TREEHOUSE_RUNTIME_RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="SDL3-CS" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.Android" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.iOS" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.Linux" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.MacOS" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.tvOS" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.Windows" Version="3.4.14.1" />
    <PackageReference Include="Veldrid" Version="4.9.0" />
  </ItemGroup>

</Project>
